CREATE EXTENSION if not exists hstore;

create table test(
  id serial PRIMARY KEY,
  bigint_col bigint,
  bigserial_col bigserial,
  bit_col bit,
  bitv_col bit varying,
  boolean_col boolean,
  box_col box,
  bytea_col bytea,
  character_col character,
  characterv_col character varying,
  cidr_col cidr,
  circle_col circle,
  date_col date,
  double_col double precision,
  inet_col inet,
  integer_col integer,
  interval_col interval,
  json_col json,
  jsonb_col jsonb,
  line_col line,
  lseg_col lseg,
  macaddr_col macaddr,
  money_col money,
  numeric_col numeric,
  path_col path,
  pg_lsn_col pg_lsn,
  point_col point,
  polygon_col polygon,
  real_col real,
  smallint_col smallint,
  smallserial_col smallserial,
  text_col text,
  time_col time,
  timestamp_col timestamp,
  tsquery_col tsquery,
  tsvector_col tsvector,
  txid_snapshot_col txid_snapshot,
  uuid_col uuid,
  xml_col xml,
  hstore_column hstore not null,
  uuid_array uuid[]
);